blank_issues_enabled: false
contact_links:
  - name: ESG_VM Discord Community Invitation
    url: https://discord.gg/RZ7Mr2vz
    about: Please ask and answer questions here.
  - name: ESG_VM Discord Community
    url: https://discord.com/channels/1189332560413720656/1189332561000935449
    about: Please ask and answer questions here.
  - name: GitHub Support
    url: https://github.com/contact?form%5Bsubject%5D=Formul%C3%A1rios+de+issues+%28beta%29
    about: GitHub Support.
