name: Enabler
description: Issue to enable other issue to be implemented
title: "[Enabler]: "
labels: ["Enabler"]
projects: ["ESG Value Mining"]
assignees:
  - 

body:
  - type: markdown
    attributes:
      value: |
        This is to promove capacity to other parts of project!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        
  - type: markdown
    attributes:
      value: |
        <div align="center">
  
        ## Requirements Description
  
        </div>

  - type: markdown
    attributes:
      value: |
        ---
  
  - type: textarea
    id: what-needs
    attributes:
      label: Enabler description
      description: Describe in details what is being implemented, and whitch issue is/are under impact.
      placeholder: Please, insert briefly, you own view about the best way to implement this.
      value: "Insert information regarding technical details!"
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Relevant additional informations
      description: Please copy and paste any relevant reference.
      render: shell
  - type: dropdown
    id: Lista_1
    attributes:
      label: Impact in Archtecture
      multiple: true
      description: Whitch part of structure this issue impacts
      options:
        - Databaset
        - Colectors
        - Orchestrators
        - Broker
        - The Nest
        - Consumer
        - All
      default: 1
    validations:
      required: true
  - type: dropdown
    id: Lista_2
    attributes:
      label: Classification
      multiple: true
      description: Whitch kind of action this issue is related for
      options:
        - Archtecture Optimization
        - Refactoring
        - Infrastructure
        - All
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        
  - type: markdown
    attributes:
      value: |
        <div align="center">
  
        ## Issue Opening Setup
  
        </div>

  - type: markdown
    attributes:
      value: |
        ---
        
  - type: dropdown
    id: criticality
    attributes:
      label: Criticality_
      description: What is the level of criticality for this issue ?
      multiple: false
      options:
        - Critical
        - Major
        - Minor
  - type: dropdown
    id: skill
    attributes:
      label: Skill_
      description: Which kind of skill would be initially necessary ?
      multiple: false
      options:
        - Arch&AI - Authentication Process
        - Arch&AI - Blockchain
        - Arch&AI - Brokers
        - Arch&AI - Cybersecurity
        - Arch&AI - Deep Learning
        - Arch&AI - Machine Learning
        - Arch&AI - Neural Net
        - Arch&AI - Payment Token
        - Arch&AI - TOGAF
        - Arch&AI - Web Scraping
        - DB - BI
        - DB - ETL
        - DB - Hadoop
        - DB - OLAP
        - DB - OLTP
        - DB - Spark
        - Ind - Advertising and Market
        - Ind - Education and Art
        - Ind - Entertainment
        - Ind - Finance
        - Ind - Health Care
        - Ind - Laws
        - Ind - Medicine
        - Ind - Non-Governmental Organizations
        - Ind - Public Management
        - Ind - Science and Research
        - Ind - Security
        - Ind - Telecom Midia and Technology
        - LP - C#
        - LP - CSS
        - LP - HTML
        - LP - Java
        - LP - JS
        - LP - Kotlin
        - LP - Lua
        - LP - Perl
        - LP - PHP
        - LP - Python
        - LP - R
        - LP - Ruby
        - LP - SQL
        - LP - VBA
        - Mgmt - Kanban
        - Mgmt - PMP
        - Mgmt - PRINCE
        - Mgmt - PRiSM
        - Mgmt - SAFe
        - Mgmt - Scrum
        - OS - Android
        - OS - Git
        - OS - iOS
        - OS - Linux
        - Sustain - Carbon Credit
        - Sustain - ESG
        - Sustain - GEE
        - Sustain - GHG Protocol
        - Sustain - Greenwashing
        - Sustain - GRI
        - Sustain - SDG(UN)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct_
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://moriblo.github.io/ESG_VM_Program/Ambient/)
      options:
        - label: I am following this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        ---
      
  - type: markdown
    attributes:
      value: |
        <div align="center">
  
        ## Project Management Part
  
        </div>

  - type: markdown
    attributes:
      value: |
        ---
  
  - type: checkboxes
    id: terms_1
    attributes:
      label: Definition of Ready
      description: Define when the requirement is ready to go on for code.
      options:
        - label: The Epic is corrected linked
          required: false
        - label: Story Points were estimated
          required: false
        - label: The description was detailed and acceptance definitions were also defined
          required: false
        - label: The responsible is already allocated
          required: false
  - type: checkboxes
    id: terms_2
    attributes:
      label: Definition of Done
      description: Define when the requirement is done to go on for final acceptance.
      options:
        - label: All the Business Rules were implemented (no check if NA)
          required: false
        - label: QA in Compliance with ISO 25010 (Software Product Quality Model) 
          required: false
        - label: The applicable Law for Protection Data was considered (no check if NA)
          required: false
        - label: The minimal encription mode between browser and server has to be https (no check if NA)
          required: false
        - label: No warnings in project building
          required: false
        - label: Unit tests implemented and ok
          required: false
        - label: Integration tests running ok
          required: false
        - label: Documentation updated
          required: false
        - label: Code Revised in pair (pull requests done and verified)
          required: false
        - label: Tests done in Chrome (no check if NA)
          required: false
        - label: Tests done in Edge (no check if NA)
          required: false
        - label: Tests done in Safari (no check if NA)
          required: false
        - label: Tests done in Firefox (no check if NA)
          required: false
        - label: UX Designer gave OK (no check if NA)
          required: false
        - label: PO gave OK (no check if NA)
          required: false
