name: No Functional Requirement
description: No Funcional Requirement Description
title: "[Requirement]: "
labels: ["NFReq"]
projects: ["ESG Value Mining"]
assignees:
  - 

body:
  - type: markdown
    attributes:
      value: |
        This is to comply with the project´s needs!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-needs
    attributes:
      label: Requirement description
      description: Describe in details what is the no funtional facility needed
      placeholder: Please, insert briefly, you own view about the best way to implement the requirement.
      value: "Insert details regarding the requirement!"
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Relevant additional informations
      description: Please copy and paste any relevant reference.
      render: shell
  - type: checkboxes
    id: terms_0
    attributes:
      label: Classification
      description: Define the kind of No Functional Requirement
      options:
        - label: Compatibility
          required: false
        - label: Reliability
          required: false
        - label: Efficiency
          required: false
        - label: Maintainability
          required: false
        - label: Portability
          required: false
        - label: Security
          required: false
        - label: Usability
          required: false
        - label: Accessibility
          required: false
        - label: Ethical
          required: false
        - label: Integration
          required: false
        - label: Interoperability
          required: false
        - label: Compliance
          required: false
  - type: checkboxes
    id: terms_1
    attributes:
      label: Definition of Ready
      description: Define when the requirement is ready to go on for code.
      options:
        - label: The Epic is corrected linked
          required: false
        - label: Story Points were estimated
          required: false
        - label: The description was detailed and acceptance definitions were also defined
          required: false
        - label: The responsible is already allocated
          required: false
  - type: checkboxes
    id: terms_2
    attributes:
      label: Definition of Done
      description: Define when the requirement is done to go on for final acceptance.
      options:
        - label: All the Business Rules were implemented (no check if NA)
          required: false
        - label: QA in Compliance with ISO 25010 (Software Product Quality Model) 
          required: false
        - label: The applicable Law for Protection Data was considered (no check if NA)
          required: false
        - label: The minimal encription mode between browser and server has to be https (no check if NA)
          required: false
        - label: No warnings in project building
          required: false
        - label: Unit tests implemented and ok
          required: false
        - label: Integration tests running ok
          required: false
        - label: Documentation updated
          required: false
        - label: Code Revised in pair (pull requests done and verified)
          required: false
        - label: Tests done in Chrome (no check if NA)
          required: false
        - label: Tests done in Edge (no check if NA)
          required: false
        - label: Tests done in Safari (no check if NA)
          required: false
        - label: Tests done in Firefox (no check if NA)
          required: false
        - label: UX Designer gave OK (no check if NA)
          required: false
        - label: PO gave OK (no check if NA)
          required: false
